name: flask-helloworld
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq


      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker Image Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
              ${{ secrets.DOCKER_USERNAME }}/flask-helloworld
              ${{ secrets.DOCKER_USERNAME }}/flask-helloworld:${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify
        run: |
          LATEST_DIGEST=$(docker manifest inspect ${{ secrets.DOCKER_USERNAME }}/flask-helloworld:latest | jq -r '.config.digest')
          RUN_NUMBER_DIGEST=$(docker manifest inspect ${{ secrets.DOCKER_USERNAME }}/flask-helloworld:${{ github.run_number }} | jq -r '.config.digest')
          
          echo "Latest Image Digest: $LATEST_DIGEST"
          echo "Run Number Image Digest: $RUN_NUMBER_DIGEST"

          if [ "$LATEST_DIGEST" == "$RUN_NUMBER_DIGEST" ]; then
            echo "Image digests match."
          else
            echo "Image digests do not match."
            exit 1
          fi